import { Component, OnInit } from '@angular/core';
import { first } from 'rxjs/operators';

import { UserService, AuthenticationService } from '../_services';

@Component({
  selector: 'app-body',
  templateUrl: './body.component.html',
  styleUrls: ['./body.component.css']
})
export class BodyComponent implements OnInit {

  //TODO autogenerated, is this what we want?
  currentUser: any;
  users: import("c:/Users/hays/thatshit/cs-capstone-2020-hie/hie-fred/src/app/_models/user").User[];
  //!!!!!

  constructor(
    private authenticationService: AuthenticationService,
    private userService: UserService
) {
    this.currentUser = this.authenticationService.currentUserValue;
}

ngOnInit() {
    this.loadAllUsers();
}

private loadAllUsers() {
  this.userService.getAll()
      .pipe(first())
      .subscribe(users => this.users = users);
}

}
